version: '3.5'

include:
  - docker-compose-db.yml
services:
  #CONFIG SERVER CONTAINER
  configServerApp:
    build:
      context: ./config-server
    image: pdf_editor_config:latest
    container_name: configServerApp
    networks:
      - server_net


  #Discovery SERVER CONTAINER
  discoveryServerApp:
    build:
      context: ./discovery-server
    image: pdf_editor_discover:latest
    container_name: discoveryServerApp
    depends_on:
      - configServerApp
    networks:
      - server_net

  # Gateway SERVER CONTAINER
  gatewayServerApp:
    build:
      context: ./gateway-server
    image: pdf-editor-gateway:latest
    container_name: gatewayServerApp
    ports:
      - "8072:8072"
    depends_on:
      - configServerApp
      - discoveryServerApp
    networks:
      - server_net
      - db_doc_net
  # DOCUMENTS SERVER CONTAINER
  documentsServerApp:
    build:
      context: ./document-service
    image: pdf-editor-document:latest
    container_name: documentsServerApp
    depends_on:
      - configServerApp
      - discoveryServerApp
      - mongodb
    networks:
      - server_net
      - db_doc_net

  # EMAIL SERVER CONTAINER
  emailServerApp:
    build:
      context: ./email-service
    image: pdf-editor-email:latest
    container_name:  emailServerApp
    depends_on:
      - configServerApp
      - discoveryServerApp
    networks:
      - server_net

  # USER SERVER CONTAINER
  usersServerApp:
    build:
      context: ./user-service
    image: pdf-editor-user:latest
    container_name: usersServerApp
    hostname: usersServerApp
    depends_on:
      - configServerApp
      - discoveryServerApp
    networks:
      - server_net

  #KEYCLOCK CONTAINER
  keyClock:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keyClock
    hostname: keyClock
    ports:
      - "7080:8080"
    networks:
      - server_net
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
networks:
  server_net:
    external: true
    name: kafka_network
  db_doc_net:
    external: true
    name: db_network

