version: '2.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: document-service
      MONGO_INITDB_ROOT_PASSWORD: pdfdocument
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: document-service
      ME_CONFIG_MONGODB_ADMINPASSWORD: pdfdocument
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: document-service
      ME_CONFIG_BASICAUTH_PASSWORD: pdfdocument
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
# Define named volumes
volumes:
  mongo-data:
    driver: local
networks:
  mongo-compose-network: