spring:
  application:
    name: "users"
  config:
    import: "configserver:http://configServerApp:8080/"
  cloud:
    config:
      enabled: true
      uri: http://configServerApp:8080
    stream:
      kafka:
        binder:
          brokers: "configBroker:9091"
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    hostname: discoveryServerApp
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    healthcheck:
      enabled: true
endpoints:
  shutdown:
    enabled: true
logging:
  level:
    com:
      userservice:
        - DEBUG
        - INFO
        - ERROR
info:
  app:
    version: 1.0.0
    description: "Service to manage user data"

