spring:
  datasource:
   url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER;IGNORECASE=TRUE;DATABASE_TO_UPPER=false;
   username: tour
   password: tour
   driver-class-name: org.h2.Driver
  jpa:
   hibernate:
     ddl-auto: create
  jackson:
    parser:
      allow-unquoted-field-names: true
  application:
    name: user-service
server:
  port: 8080
rest-template:
  timeout: 600000
  pool-size: 5


