spring:
  application:
    name: discoveryserver
  config:
    import: "configserver:http://configServerApp:8080/"
  cloud:
    config:
      enabled: true
      uri: "http://configServerApp:8080"
    stream:
      kafka:
        binder:
          brokers: configBroker:9091
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"