spring:
  application:
    name: "documents"
  config:
    import: "configserver:http://configServerApp:8071/"
  cloud:
    config:
      enabled: true
      uri: "http://configServerApp:8071"
    stream:
      kafka:
        binder:
          brokers: configBroker:9091
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

topics:
  download-document-name: download-document-event

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"

