spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: local

topics:
  download-document-name: download-document-event
  configs: "git-configs"
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: local
  jackson:
    parser:
      allow-unquoted-field-names: true
  application:
    name: "documents"
  kafka:
    topic: download-document-event
    template:
      default-topic: download-document-event
    producer:
      bootstrap-server: localhost:9092, localhost:9093, localhost:9094
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
      properties:
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        retries: 10
        retry.backoff.ms: 100000



