spring:
  application:
    name: "documents"
  config:
    import: "configserver:http://configServerApp:8071/"
  cloud:
    config:
      enabled: true
      uri: "http://configServerApp:8071"
    stream:
      kafka:
        binder:
          brokers: configBroker:9091
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: false
      alphanumeric-ids:
        enabled: true
      httpclient:
        connection-timeout: 1000


topics:
  download-document-name: download-document-event

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    hostname: discoveryServerApp
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/
    healthcheck:
      enabled: true
endpoints:
  shutdown:
    enabled: true
logging:
  level:
    com:
      documentservice:
        - DEBUG
        - INFO
        - ERROR
info:
  app:
    version: 1.0.0
    description: "Service to manage documents data"
resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      users:
        register-health-indicator: true
        sliding-window-size: 5
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 60
  retry:
    retryAspectOrder: 2
