spring:
  jackson:
    parser:
      allow-unquoted-field-names: true
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://pdf_document:pdfdocument@document-service.ux4nj27.mongodb.net/?retryWrites=true&w=majority&appName=document-service
      database: documents
server:
  port: 8082
rest-template:
  timeout: 600000
  pool-size: 5


