
name: documents server CI/CD

on:
  push:
    paths:
      - "document-service/**"
    branches: [ "master" ]
jobs:
  server:
    name: Job for 'document-service' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file document-service/pom.xml
      - name: build  document service image
        run: docker compose build  document_service
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag document_service ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:document_service
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:document_service