
name: gateway server server CI/CD

on:
  push:
    paths:
      - "gateway-server/**"
    branches: [ "master" ]
jobs:
  server:
    name: Job for 'gateway-server' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file gateway-server/pom.xml
      - name: build  document service image
        run: docker compose build  gateway_server
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag gateway_server ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:gateway_server
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:gateway_server