spring:
  application:
    name: "configserver"
  profiles:
    active: git  #native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tswlun002/pdf-editor-configs.git"
        #native:
          #search-locations: "classpath:/config"
          default-label: main
          timeout: 10
          clone-on-start: true
          force-pull: true
server:
  port: 8071
encrypt:
  key: 7E93D539EAA5C42F8523AB1627D1B


