server:
  port: 8080
eureka:
  instance:
    hostname: discoveryServerApp
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/