#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://keyClock:8080/realms/master/protocol/openid-connect/certs"
resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 5
      wait-duration-in-open-state: 20000
      permitted-number-of-calls-in-half-open-state: 3
      failure-rate-threshold: 60