spring:
  profiles:
    active: local

---
spring:
  application:
    name: "email"
  config:
    import: "configserver:http://configServerApp:8071/"
  jackson:
    parser:
      allow-unquoted-field-names: true
  cloud:
    config:
      enabled: true
      uri: http://configServerApp:8071
    stream:
      kafka:
        binder:
          brokers: "configBroker:9091"
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

topics:
  retry: "download-document-event.RETRY"
  dead: "download-document-event.DEAD"

server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    hostname: discoveryServerApp
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/
    healthcheck:
      enabled: true
endpoints:
  shutdown:
    enabled: true
info:
  app:
    version: 1.0.0
    description: "Service to send emails"