
name: config server server CI/CD

on:
  workflow_dispatch:
#  push:
#    paths:
#      - "config-server/**"
#    branches: [ "master" ]
jobs:
  server:
    name: Job for 'config-server' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file config-server/pom.xml
      - name: build  document service image
        run: docker compose -f docker-compose-servers.yml --project-name config_server build  configServerApp
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag config_server ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:config_server
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:config_server
