
name: discovery server server CI/CD

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "discovery-server/**"
  #   branches: [ "master" ]
jobs:
  server:
    name: Job for 'discovery-server' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file discovery-server/pom.xml -DskipTests
      - name: build  document service image
        run: docker compose -f docker-compose-servers.yml  build  discoveryServerApp
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag pdf_editor_discover:latest ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:discovery_servery
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:discovery_servery
