
name: email server CI/CD

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "email-service/**"
  #   branches: [ "master" ]
jobs:
  server:
    name: Job for 'email-service' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file email-service/pom.xml -DskipTests
      - name: build  email service image
        run: docker compose -f docker-compose-servers.yml build  emailServerApp
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag pdf-editor-email:latest ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:email_service
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:email_service
