
name: user server CI/CD

on:
  push:
    paths:
      - "user-service/**"
    branches: [ "master" ]
jobs:
  server:
    name: Job for 'user-service' folder

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: install back-end
        run: mvn -B  install --file user-service/pom.xml
      - name: build  user service image
        run: docker compose build  user_service
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: push to Docker Hub
        run: |
          docker tag user_service ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:user_service
          docker push ${{secrets.DOCKERHUB_USERNAME}}/pdf-editor:user_service
